# **a_tensor_initialization.py**

In [3]:
import torch

In [4]:

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')    ##대문자로 시작하는 텐서는 float32
print(t1.dtype)   # >>> torch.float32         ##텐서의 타입
print(t1.device)  # >>> cpu                   ##텐서가 위치한 장치(cpu or gpu)
print(t1.requires_grad)  # >>> False          ##텐서에 대한 기울기가 계산되지 않음 -> 성능 up
print(t1.size())  # torch.Size([3])           ##텐서의 사이즈
print(t1.shape)   # torch.Size([3])           ##텐서의 사이즈

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))       ##gpu로 텐서를 올리는 방법
# or you can use shorthand
# t1_cuda = t1.cuda()                         ##같은 의미의 짧은 코드
t1_cpu = t1.cpu()                             ##cpu로 텐서 올기기

print("#" * 50, 1)


torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1


- torch.Tensor() 함수는 무조건 자료형이 float32이다.

In [5]:
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')    ##소문자로 시작하는 텐서는 리스트 내 원소 타입의 자료형을 가짐
print(t2.dtype)  # >>> torch.int64            ##1, 2, 3은 정수이므로 int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


- torch.tensor() 함수는 주어진 리스트 내 원소 타입의 자료형을 가진다.


In [6]:
a1 = torch.tensor(1)  # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)    ##그냥 숫자 -> size []인 0차원,  [] 안에 있어야 텐서임

a2 = torch.tensor([1])  # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)    ##size [1]인 1차원 텐서

a3 = torch.tensor([1, 2, 3, 4, 5])  # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)    ##size [5]인 1차원 텐서

a4 = torch.tensor([[1], [2], [3], [4], [5]])  # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)    ##size [5, 1]인 2차원 텐서

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)    ##size [3, 2]인 2차원 텐서

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)    ##size [3, 2, 1]인 3차원 텐서

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)    ##size [3, 1, 2, 1]인 4차원 텐서

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)    ##size [3, 1, 2, 3]인 4차원 텐서

a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)    ##size [3, 1, 2, 3, 1]인 5차원 텐서

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)    ##size [4, 5]인 2차원 텐서

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)    ##size [4, 1, 5]인 3차원 텐서
                              ##콤마의 개수로 판단하면 편함

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
                              ##동일한 차원은 반드시 같은 사이즈를 가져야하므로 error 발생

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

- 콤마의 개수로 텐서의 차원을 판단하면 편하고, 동일한 차원은 반드시 같은 사이즈를 가져야한다.
- 따라서 마지막 a11은 에러가 발생한다. 그 전 텐서들은 잘 출력됐고, 원 코드에서 에러 발생 부분에 주석처리가 안되어있었기 때문에 코드를 그대로 유지하였다.

# **b_tensor_initialization_copy.py**

In [7]:
import torch
import numpy as np

In [8]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)           ##리스트 l1을 torch.Tensor()로 변환 (dtype: float32)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)           ##리스트 l2를 torch.tensor()로 변환 (데이터 복사, dtype: int64)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)        ##리스트 l3를 torch.as_tensor()로 변환 (파이썬 리스트의 경우 데이터 복사)

l1[0] = 100                     ##l1, l2, l3의 첫번째 요소를 100으로 변경
l2[0] = 100
l3[0] = 100

print(t1)                       ##t1은 l1과 무관한 독립적인 텐서 (데이터 복사, 영향 X)
print(t2)                       ##t2는 l2와 무관한 독립적인 텐서 (데이터 복사, 영향 X)
print(t3)                       ##t3는 l3와 무관한 독립적인 텐서 (데이터 복사, 영향 X)

print("#" * 100)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################


- torch.as_tensor()는 넘파이 배열이나 텐서를 입력으로 받을 때 메모리 참조를 시도하지만, 파이썬 리스트를 입력으로 받을 때는 데이터를 복사한다. 그래서 l3를 변경해도 t3에는 그 변화가 반영되지 않는다.



In [9]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)           ##넘파이 배열 l4를 torch.Tensor()로 변환 (데이터 복사, dtype: float32)

l5 = np.array([1, 2, 3])        
t5 = torch.tensor(l5)           ##넘파이 배열 l5를 torch.tensor()로 변환 (데이터 복사, dtype: int64)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)        ##넘파이 배열 l6를 torch.as_tensor()로 변환 (데이터 참조, dtype: int64)

l4[0] = 100                     ### l4, l5, l6의 첫 번째 요소를 100으로 변경
l5[0] = 100
l6[0] = 100

print(t4)                       ##t4는 l4와 무관한 독립적인 텐서 (데이터 복사, 영향 X)
print(t5)                       ##t5는 l5와 무관한 독립적인 텐서 (데이터 복사, 영향 X)
print(t6)                       ##t6는 넘파이 배열 l6와 메모리를 공유하므로 l6의 변경이 t6에도 반영됨


tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


- torch.tensor(): 데이터를 항상 복사하여 새로운 텐서를 생성한다. 원본 데이터와 독립적인 텐서를 생성하고자 할 때 사용한다.
- torch.as_tensor(): 데이터 복사 없이 참조를 사용해 텐서를 생성한다. 메모리를 효율적으로 사용하거나 원본 데이터를 공유하고자 할 때 사용한다.

# **c_tensor_initialization_constant_values.py**

In [10]:
import torch


In [11]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)      ##크기가 5인 모든 값이 1인 텐서 생성 (dtype: float32)  
t1_like = torch.ones_like(input=t1)                 ##t1과 동일한 shape을 가지는 모든 값이 1인 텐서 생성, dtype과 device도 동일 (float32, cpu)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


- torch.ones(*size)는 크기가 n인 모든 값이 1인 텐서를 생성한다.
- torch.ones_like(input_tensor)는 input_tensor의 shape, dtype, device 속성을 그대로 복사하여 모든 값이 1인 새로운 텐서를 생성한다.

In [12]:
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)        ##크기가 6인 모든 값이 0인 텐서 생성 (dtype: float32)
t2_like = torch.zeros_like(input=t2)                    ##t2와 동일한 shape을 가지는 모든 값이 0인 텐서 생성, dtype과 device도 동일 (float32, cpu)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


- torch.zeros(*size)는 크기가 n인 모든 값이 0인 텐서를 생성한다.
- torch.zeros_like(input_tensor)는 input_tensor의 shape, dtype, device 속성을 그대로 복사하여 모든 값이 0인 새로운 텐서를 생성한다.

In [26]:
t3 = torch.empty(size=(4,))  # or torch.zeros(4)    ##크기가 4인 텐서 생성, 메모리만 할당하고 초기화는 하지 않음
t3_like = torch.empty_like(input=t3)                ##t3와 동일한 shape을 가지는 텐서 생성, t3와 똑같이 초기화는 안되어 있음
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

tensor([0., 0., 3., 0.])
tensor([1.0000, 4.4766, 3.0000, 0.0000])


- torch.empty(*size): 크기가 n인 텐서를 생성하지만 초기화하지 않는다. 즉, 텐서의 값은 임의의 값이나 이전 메모리 상태에 따라 결정된다.
- torch.empty_like(input_tensor): t3와 동일한 크기 및 dtype을 가진 텐서를 생성하되, 역시 초기화되지 않은 상태로 텐서를 생성한다.
- torch.empty()나 torch.empty_like()에서 출력되는 값은 비결정적이며, 이전 메모리 상태에 따라 달라진다.


In [27]:
t4 = torch.eye(n=3)         ##n * n 크기의 단위 행렬 생성(대각선 1, 나머지 0)
print(t4)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


- torch.eye(n): 크기가 n * n인 단위 행렬을 생성한다. 단위 행렬은 대각선에 있는 값이 모두 1이고, 나머지 값은 0이다.

# **d_tensor_initialization_random_values.py**

In [28]:
import torch

In [30]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)           ##10 이상 20 미만의 정수 중에서 랜덤 값을 가지는 1x2 텐서 생성

t2 = torch.rand(size=(1, 3))
print(t2)           ##0과 1 사이에서 균등분포로 랜덤 값을 가지는 1x3 텐서 생성

t3 = torch.randn(size=(1, 3))
print(t3)           ##평균이 0, 표준편차가 1인 정규분포에서 랜덤 값을 가지는 1x3 텐서 생성

tensor([[17, 14]])
tensor([[0.7178, 0.4226, 0.7910]])
tensor([[-0.0641,  0.4824,  0.1907]])


- torch.randint(low, high, size): low 이상 high 미만의 정수에서 무작위 값을 추출하여 size 크기의 정수형 텐서를 생성한다.
- torch.rand(size): 균등 분포인 0과 1 사이의 무작위 값을 추출하여 size 크기의 텐서를 생성한다.
- torch.randn(size): 정규 분포(평균=0, 표준편차=1)에서 무작위 값을 추출하여 size 크기의 텐서를 생성한다.

In [31]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)           ##평균이 10.0, 표준편차가 1.0인 정규 분포에서 무작위 값을 가지는 3x2 텐서 생성

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)           ##0.0에서 5.0까지 균등하게 나누어 3개의 값을 가지는 텐서 생성

t6 = torch.arange(5)
print(t6)           ##0부터 4까지의 정수를 순차적으로 가지는 텐서 생성

print("#" * 30)

tensor([[ 8.4770,  9.6105],
        [ 9.4288,  9.1313],
        [11.4126,  9.5816]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################


- torch.normal(mean, std, size): 평균이 mean, 표준편차가 std인 정규 분포에서 무작위 값을 추출하여 size 크기의 텐서를 만든다.
- torch.linspace(start, end, steps): start에서 end까지의 구간을 steps개의 값으로 균등하게 나누어 텐서를 생성한다. (start-end 구간을 steps등분한다고 생각)
- torch.arange(start, end, steps): start부터 (end-1)까지의 정수를 순서대로 가지는 1차원 텐서를 생성한다. 위 코드와 같이 end만 지정한다면, start = 0, steps = 1이 default 값이다. 

In [34]:
torch.manual_seed(1729)     ##난수 생성기의 시드를 고정하여 동일한 무작위 값이 생성되도록 설정
random1 = torch.rand(2, 3)
print(random1)              ##시드 1729의 첫번째 랜덤 텐서

random2 = torch.rand(2, 3)
print(random2)              ##시드 1729의 두번째 랜덤 텐서

print()

torch.manual_seed(1729)     ##다시 난수 생성기의 시드를 위와 같은 1729로 고정
random3 = torch.rand(2, 3)
print(random3)              ##위와 똑같이 첫번째 랜덤 텐서의 결과가 나옴

random4 = torch.rand(2, 3)
print(random4)              ##위와 똑같이 두번째 랜덤 텐서의 결과가 나옴

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


- torch.manual_seed(seed): 난수 생성기의 시드를 고정하여 실행할 때마다 동일한 난수 값을 생성한다. 시드를 똑같이 설정하면 같은 결과를 다시 얻을 수 있다.

# **e_tensor_type_conversion.py**

In [35]:
import torch

In [37]:
a = torch.ones((2, 3))
print(a.dtype)              ##default 자료형: float32

b = torch.ones((2, 3), dtype=torch.int16)
print(b)                    ##int16 자료형의 텐서로 생성

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)                    ##[2,3] 크기의 0~20 사이의 값을 가지는 float64 텐서 생성

d = b.to(torch.int32)
print(d)                    ##b 텐서를 int32로 변환하여 d 텐서 생성

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


- .to(torch.xxxx) 또는 dtype=torch.xxxx 옵션을 통해 텐서의 자료형을 설정할 수 있다.

In [39]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)        ##double(float64) 타입의 텐서 생성
short_e = torch.ones(10, 2). type(dtype=torch.short)    ##short(int16) 타입의 텐서 생성

print(double_d.dtype)   
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)    ##double(float64) 타입의 텐서 생성
short_g = double_f.to(torch.short)              ##short(int16) 타입의 텐서 생성
print((double_f * short_g).dtype)               ##두 텐서의 곱셈 연산 결과는 더 높은 정밀도를 가지는 자료형(double)으로 정해짐

torch.float64
torch.int16
torch.float64


- torch.ones(), torch.zeros(), torch.tensor() 등을 통해 다양한 텐서를 생성하고, dtype을 지정하여 자료형을 설정할 수 있다.
- .double(), .short()는 텐서를 double 또는 short 자료형으로 변환할 수 있다.
- .to()와 .type()은 자료형을 명시적으로 변환하는 다른 방법이다.
- 두 텐서의 곱셈 연산 결과는 더 높은 정밀도를 가지는 자료형으로 정해진다.

# **f_tensor_operations.py**

In [2]:
import torch

In [6]:
t1 = torch.ones(size=(2, 3))            ##  [[1., 1., 1.],
                                        ##   [1., 1., 1.]]

t2 = torch.ones(size=(2, 3))            ##  [[1., 1., 1.],
                                        ##   [1., 1., 1.]]

t3 = torch.add(t1, t2)              ##텐서의 덧셈
t4 = t1 + t2                        ##같은 의미의 코드
print(t3)
print(t4)

print("#" * 30)


t5 = torch.sub(t1, t2)              ##텐서의 뺄셈
t6 = t1 - t2                        ##같은 의미의 코드
print(t5)
print(t6)

print("#" * 30)


t7 = torch.mul(t1, t2)              ##텐서의 곱셈
t8 = t1 * t2                        ##같은 의미의 코드
print(t7)
print(t8)

print("#" * 30)


t9 = torch.div(t1, t2)              ##텐서의 나눗셈
t10 = t1 / t2                       ##같은 의미의 코드
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


- 두 텐서의 덧셈: torch.add() or +
- 두 텐서의 뺄셈: torch.sub() or -
- 두 텐서의 곱셈: torch.mul() or *
- 두 텐서의 나눗셈: torch.div() or /
- 두 텐서가 서로 자료형이 다르면 더 높은 정밀도의 자료형을 따름

# **g_tensor_operations_mm.py**

In [7]:
import torch

In [11]:
t1 = torch.dot(             ##1차원 텐서간의 dot product 계산
    torch.tensor([2, 3]), 
    torch.tensor([2, 1])
)
print(t1, t1.size())        ##2*2 + 3*1 = 7, 그냥 스칼라 값이기 때문에 0차원, size는 []

print()                     ##가독성을 위해 추가한 코드

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)       ##2차원 텐서간의 행렬 곱셈
print(t4, t4.size())        ##결과는 [2, 2] size의 행렬

print()                     ##가독성을 위해 추가한 코드

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)      ##3차원 텐서 간의 배치 행렬 곱셈
print(t7.size())            ##결과는 [10, 3, 5] size의 행렬

tensor(7) torch.Size([])

tensor([[ 0.2716,  0.2314],
        [-0.1935, -1.3399]]) torch.Size([2, 2])

torch.Size([10, 3, 5])


- torch.dot(): 1차원 텐서 간의 내적 연산을 수행한다. 결과는 스칼라 값이며, 크기는 없다.
- torch.mm(): 2차원 텐서 간의 행렬 곱셈을 수행한다. (n\*m) by (m\*p) --> (n\*p)
- torch.bmm(): 3차원 텐서 간의 배치 행렬 곱셈을 수행한다. (b\*n\*m) by (b\*m\*p) --> (b\*n\*p)

# **h_tensor_operations_matmul.py**

In [12]:
import torch

In [13]:
# vector x vector: dot product
t1 = torch.randn(3)                     ##크기 [3,]인 랜덤 벡터
t2 = torch.randn(3)                     ##크기 [3,]인 랜덤 벡터
print(torch.matmul(t1, t2).size())  # torch.Size([])
                                        ##벡터 간의 내적 (스칼라 값, 크기 [])
                                        
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)                  ##크기 [3,4]인 행렬
t4 = torch.randn(4)                     ##크기 [4,]인 벡터
print(torch.matmul(t3, t4).size())  # torch.Size([3])   
                                        ##행렬의 각 행에 대해 벡터의 내적 계산(크기 [3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)              ##크기 [10, 3,4]인 행렬
t6 = torch.randn(4)                     ##크기 [4,]인 벡터
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])
                                        ##t5의 각 배치는 [3,4] 크기의 행렬이고, t6 벡터와 곱하면 [3,]크기의 벡터가 된다. 각 배치에 대해 [3,] 크기의 벡터 10개가 생성되므로 크기는 [10,3]

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)              ##크기 [10, 3,4]인 행렬
t8 = torch.randn(10, 4, 5)              ##크기 [10, 4,5]인 행렬
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])
                                        ##bmm 곱셈에 따라 [10, 3, 5]가 된다.
                                        ##각 배치끼리의 행렬 곱셈

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)              ##크기 [10, 3,4]인 행렬
t10 = torch.randn(4, 5)                 ##크기 [4,5]인 행렬
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])
                                        ##배치 행렬과 일반 행렬간의 곱셈
                                        ##t9의 각 배치와 t10간의 행렬 곱셈
                                        ##결과 사이즈는 [10, 3, 5]

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


- 벡터 간 곱 (Dot Product): 두 벡터의 내적은 스칼라 값을 반환하며, 크기는 []이다.
- 행렬과 벡터 곱: 행렬의 각 행과 벡터의 내적을 통해 새로운 벡터를 만든다.
- 배치 행렬 곱: 여러 배치의 행렬을 동시에 계산하며, 각 배치에서 독립적인 행렬 곱이 이루어진다.
- torch.matmul()은 상황에 맞게 벡터, 행렬, 배치 행렬 간의 연산을 자동으로 수행한다.
- t7, t8는 서로 독립적인 배치 간의 곱, t9, t10는 고정된 행렬과 여러 배치 행렬 간의 곱이다.

# **i_tensor_broadcasting.py**

In [2]:
import torch

In [5]:
t1 = torch.tensor([1.0, 2.0, 3.0])              ##1차원 텐서
t2 = 2.0                                        ##스칼라 값
print(t1 * t2)                                  ##t1의 각 요소에 t2(스칼라 값)을 곱함

print("#" * 50, 1)


t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])   ##2차원 텐서
t4 = torch.tensor([4, 5])                       ##1차원 텐서
print(t3 - t4)                                  ##t3에서 t4를 브로드캐스팅하여 뺌. t4를 각행에 반복 적용

print("#" * 50, 2)


t5 = torch.tensor([[1., 2.], [3., 4.]])         ##2차원 텐서
print(t5 + 2.0)  # t5.add(2.0)                  ##t5의 갹 요소에 +2.0
print(t5 - 2.0)  # t5.sub(2.0)                  ##t5의 갹 요소에 -2.0
print(t5 * 2.0)  # t5.mul(2.0)                  ##t5의 갹 요소에 *2.0
print(t5 / 2.0)  # t5.div(2.0)                  ##t5의 갹 요소에 /2.0

print("#" * 50, 3)

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3


- 텐서는 차원이 달라도 브로드캐스팅을 통해 사칙연산이 가능하다.

In [6]:
def normalize(x):
  return x / 255        ##보통 이미지 데이터를 정규화할 때 사용하는 방식(ex. 픽셀값)


t6 = torch.randn(3, 28, 28)     ##[3, 28, 28] 사이즈의 무작위 텐서(ex. 3채널{RGB} 이미지)
print(normalize(t6).size())     ##정규화한 텐서의 크기 출력

print("#" * 50, 4)

torch.Size([3, 28, 28])
################################################## 4


- nomalize() 함수를 통해 값들을 정규화시킬 수 있다.
- 정규화하면, 값만 정규화될 뿐 텐서의 크기에는 영향을 주지 않는다.

In [7]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
                    ##[[1+3, 2+1], [0+3, 3+1]]
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
                    ##[[1+5, 2+5], [0+2, 3+2]]
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
                    ##[[3+5, 1+5], [3+2, 1+2]]
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])
                    ##[[1+7, 2+7], [0+7, 3+7]]

print("#" * 50, 5)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5


- 각 텐서의 크기가 다르지만, 브로드캐스팅에 의해 자동으로 크기가 맞춰져 연산이 수행된다.

In [8]:
t11 = torch.ones(   4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(   4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(   4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(   3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)


t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(   3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(      1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])


# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(   3, 1, 1)         ##에러 발생 이유: 어느 한쪽이 1이거나 서로 같아야 함
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7


- 브로드캐스팅 규칙은 텐서의 차원 크기가 1이거나 존재하지 않을 때 자동으로 복제하여 연산을 가능하게 만든다.
- 위 코드에서처럼 마지막 차원부터 확인하면 편하다. 어느 한쪽이 1이거나, 서로 같으면 연산이 가능하고, 어느 한쪽이 가지고 있지 않은 차원을 다른 쪽이 가지고 있다면 그 차원의 사이즈를 그대로 가져온다.
- t25, t26처럼 같은 차원이 2와 3으로 다르면 연산이 불가능하다.

In [9]:
t27 = torch.ones(4) * 5             ##[1., 1., 1., 1.]의 각 요소에 *5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)             ##[5., 5., 5., 5.]의 각 요소에 ^2
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)             ##a의 각 요소를 exp의 대응되는 요소로 제곱(1^1, 2^2, 3^3, 4^4)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


- torch.pow() 함수는 제곱을 위해 사용한다.

# **j_tensor_indexing_slicing.py**

In [10]:
import torch

In [13]:
x = torch.tensor(
  [[ 0,  1,  2,  3,  4],
   [ 5,  6,  7,  8,  9],
   [10, 11, 12, 13, 14]]
)
                                                ##교집합을 찾는다고 생각하면 된다
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])      ##1행
print(x[:, 1])  # >>> tensor([1, 6, 11])        ##모든 행, 1열의 교집합
print(x[1, 2])  # >>> tensor(7)                 ##1행, 2열의 교집합
print(x[:, -1])  # >>> tensor([4, 9, 14)        ##모든 행, 마지막 열의 교집합

print("#" * 50, 1)


print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])    ##1행~마지막행 
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])    ##1행~마지막행, 3열~마지막열의 교집합

print("#" * 50, 2)


y = torch.zeros((6, 6))         ##모두 0.인 6x6 행렬
y[1:4, 2] = 1                   ##1행~3행, 2열의 교집합을 1로 변경
print(y)                        

print(y[1:4, 1:4])              ##1행~3행, 1열~3열의 교집합을 출력

print("#" * 50, 3)


z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])                    ##0행~1행
print(z[1:, 1:3])               ##1행~마지막행, 1열~2열의 교집합
print(z[:, 1:])                 ##모든 행, 1열~마지막열의 교집합

z[1:, 1:3] = 0                  ##1행~마지막행, 1열~2열의 교집합을 0으로 변경
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


- ':'기호 -> 모든 행 또는 모든 열
- 숫자 (ex.3) -> 그 행 또는 그 열 (ex.3행 또는 3열)
- -1 -> 마지막 행 또는 마지막 열 의미
- 숫자+':' (ex.3:) -> 숫자행 포함 그 이후 또는 숫자열 포함 그 이후 (ex.3행\~마지막행 또는 3열\~마지막열)
- 숫자1+':'+숫자2 (ex.1:4) -> 숫자1행\~(숫자2 - 1)행 또는 숫자1열\~(숫자2 - 1)열 (ex.1행\~3행 또는 1열\~3열)
- ':'+숫자 (ex.:2) -> 0행\~(숫자-1)행 또는 0열\~(숫자-1)열 (ex. 0행\~1행 또는 0열\~1열)

# **k_tensor_reshaping.py**

In [14]:
import torch

In [16]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)


t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1


- 데이터는 변경되지 않고, shape만 바뀐다.
- 연속적인 텐서: view()만 사용할 수 있고, 메모리 참조를 한다.
- 불연속적 텐서: view(), reshape() 모두 사용할 수 있고, 메모리 카피를 한다.

In [20]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)


# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


- squeeze(dim): 괄호 안에 dim을 지정하지 않으면 크기가 1인 차원을 모두 없애고, dim을 지정하면 그 차원만 없앤다.
- unsqueeze(dim): 괄호 안에 dim을 지정해야만 하고, dim을 지정하면 그 위치에 차원을 추가한다.

In [21]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)


# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)       ##1번째 차원 이상의 모든 차원이 평탄화, 즉 2차원 텐서로 변환

print(t16)
print(t17)

print("#" * 50, 4)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


- torch.flatten(): 옵션이 없다면 텐서를 1차원으로 평탄화해준다. start_dim을 설정하면 평탄화할 차원의 시작점을 조정할 수 있다.

In [24]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])


# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

print()             ##가독성을 위해 추가한 코드

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


- torch.permute(input, dims): 텐서의 차원의 순서를 변경하는데 사용, 각 차원을 원하는 순서로 재배열
- torch.transpose(tensor, dim0, dim1): 텐서를 전치하는데 사용, dim0 차원과 dim1 차원이 바뀜, 모든 차원에 대해 사용 가능
- torch.t(tensor): 텐서를 전치하는데 사용, 2차원 텐서에 사용 가능

# **l_tensor_concat.py**

In [25]:
import torch

In [27]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)     ##1번째 차원에 concat -> [2, 6, 3]
print(t4.shape)

print("#" * 50, 1)


t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)         ##0번째 차원에 concat -> [8]
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2


- torch.cat(tensors, dim) == torch.concat(tensors, dim)

In [28]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)            ##0번째 차원에 concat -> [4, 3]
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)            ##1번째 차원에 concat -> [2, 6]
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3


In [30]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)         ##0번째 차원에 concat -> [6, 3]
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)         ##1번째 차원에 concat -> [2, 9]
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4


In [31]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)              ##0번째 차원에 concat -> [2, 2, 3]
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)              ##1번째 차원에 concat -> [1, 4, 3]
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)              ##2번째 차원에 concat -> [1, 2, 6]
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


- torch.cat(tensors, dim) 함수는 주어진 텐서들을 특정 차원에서 연결하여 새로운 텐서를 생성한다.

# **m_tensor_stacking.py**

In [32]:
import torch

In [35]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])           ##[2, 3]
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])        ##[2, 3]

t3 = torch.stack([t1, t2], dim=0)       ##새 차원을 만들고 concat을 하는 것이라 생각하면 됨
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))           ##t3과 t4는 동일함

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1


In [36]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


- torch.stack(tensors, dim): dim 위치에 새 차원을 하나 만들고, concat을 하는 것과 동일한 결과를 갖는다.

# **n_tensor_vstack_hstack.py**

In [37]:
import torch

In [41]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))             ##수직으로 쌓는다고 생각하면 됨
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])


t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)


t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1


- torch.vstack(): 주어진 텐서를 수직으로 쌓아 새로운 텐서를 만든다.

In [104]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))              ##수평으로 붙인다고 생각하면 됨
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


- torch.hstack(): 주어진 텐서를 수평으로 쌓아 새로운 텐서를 만든다.

# **숙제 후기**

- 자료로 나눠주신 jupyter notebook 단축키 외에, markdown의 글씨 크기 설정, 글씨 두께 설정 등 기본적인 사용법에 대해서 알 수 있었다.
- 원본 코드에 작성된 주석과 구분할 수 있도록 ##으로 주석을 달아놓았다.
- 특강을 듣고 이 코드를 다시 보니, 이 코드들이 제일 기본적이면서 중요한 코드라는 생각이 들었다.
- 코드에 써넣은 주석과, 코드 아래 markdown으로 작성한 설명을 이 정도로 쓰면 괜찮은 것인지 궁금하다.
- 이렇게 과제에 주석과 설명을 잘 적어놓으면 나중에 다시 찾아볼 때나 궁금한 게 생겼을 때 매우 도움이 될 것 같다.